name: Self-test
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm test
      - run: npm run build

      # Check the build didn't result in any changes
      - uses: pulumi/git-status-check-action@v1

  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        name: Run glob-action locally
        id: glob
        with:
          operation: "copy"
          files: |
            *.yml
            *.json
            *.js
            src/**/*.ts
            !src/**/*.test.ts
          source: "."
          destination: "sources"

      - uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources

      - id: source-files
        run: |
          echo -n "count=" >> $GITHUB_OUTPUT &&
            find sources -type f | wc -l >> $GITHUB_OUTPUT

      - if: steps.source-files.outputs.count != '7'
        run: |
          echo "Unexpected change count: ${{ steps.source-files.outputs.count }}"
          find sources -type file
          exit 1
